In [20]:
import numpy as np
a=[1,2,3]
print(a)

[1, 2, 3]


In [3]:
a[1]

2

In [13]:
a = np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
a = np.array([[1,2],[3,4],[5,6]],dtype=np.float64)
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [10]:
a.ndim

2

In [22]:
np.zeros((3,4))


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
l=range(5)
l

range(0, 5)

In [24]:
np.arange(5)

array([0, 1, 2, 3, 4])